"""add users and link applications to users

Revision ID: 29d20235d7ee
Revises: d9c69115a0e0
Create Date: 2026-02-01 08:18:22.905957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text



# revision identifiers, used by Alembic.
revision: str = '29d20235d7ee'
down_revision: Union[str, Sequence[str], None] = 'd9c69115a0e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('applications', sa.Column('user_id', sa.Integer(), nullable=True))
    op.execute(
        text(
            "INSERT INTO users (email, hashed_password) "
        "VALUES ('legacy@local', 'LEGACY') "
        "ON CONFLICT (email) DO NOTHING"
        )
    )
    op.execute(
    text(
        "UPDATE applications "
        "SET user_id = (SELECT id FROM users WHERE email = 'legacy@local') "
        "WHERE user_id IS NULL"
    )
)
    op.alter_column('applications', 'user_id', nullable=False)
    op.create_foreign_key("fk_applications_user_id_users", 'applications', 'users', ['user_id'], ['id'],ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'user_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
